package com.example.notificationservice.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

import java.time.LocalDateTime;

/**
 * Notification Entity Record for R2DBC
 */
@Table("notifications")
public record Notification(
    @Id Long id,
    Long userId,
    String title,
    String message,
    NotificationType notificationType,
    NotificationChannel channel,
    NotificationStatus status,
    Boolean isRead,
    LocalDateTime createdAt,
    LocalDateTime readAt,
    String metadata
) {
    
    // Static factory for creating new notifications
    public static Notification create(Long userId, String title, String message, 
                                    NotificationType notificationType, NotificationChannel channel) {
        return new Notification(
            null, // id generated by DB
            userId,
            title,
            message,
            notificationType,
            channel,
            NotificationStatus.PENDING,
            false,
            LocalDateTime.now(),
            null,
            null
        );
    }
    
    // Wither methods for immutability
    public Notification withId(Long id) {
        return new Notification(id, userId, title, message, notificationType, channel, status, isRead, createdAt, readAt, metadata);
    }

    public Notification withStatus(NotificationStatus status) {
        return new Notification(id, userId, title, message, notificationType, channel, status, isRead, createdAt, readAt, metadata);
    }

    public Notification withIsRead(Boolean isRead) {
        return new Notification(id, userId, title, message, notificationType, channel, status, isRead, createdAt, readAt, metadata);
    }

    public Notification withReadAt(LocalDateTime readAt) {
        return new Notification(id, userId, title, message, notificationType, channel, status, isRead, createdAt, readAt, metadata);
    }

    public Notification withMetadata(String metadata) {
        return new Notification(id, userId, title, message, notificationType, channel, status, isRead, createdAt, readAt, metadata);
    }
}
